# Generated by Django 4.2.1 on 2023-06-04 11:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_productcategories_remove_invoiceitem_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('voucher_type', models.CharField(choices=[('GV', 'General Voucher'), ('PV', 'Payment Voucher'), ('RV', 'Receipt Voucher')], max_length=2)),
                ('voucher_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='myapp.main_account')),
            ],
        ),
    ]
