# Generated by Django 4.2.1 on 2023-06-04 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_ledger_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherdetail',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='myapp.subaccount'),
        ),
    ]
