# Generated by Django 4.2.1 on 2023-06-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_subaccount_opening_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subaccount',
            old_name='sub_account',
            new_name='main_account',
        ),
    ]
