# Generated by Django 4.2.1 on 2023-06-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_subaccount_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='opening_qty',
            field=models.IntegerField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
