# Generated by Django 4.2.1 on 2023-06-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_product_opening_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
