# Generated by Django 4.2.1 on 2023-06-05 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_inventory_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='product',
            new_name='inv_product',
        ),
    ]
